"""Update db

Revision ID: cdc2a8d682fa
Revises: e9b9cf9be65c
Create Date: 2026-02-11 23:56:41.180699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdc2a8d682fa'
down_revision = 'e9b9cf9be65c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('salary_range', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('interview_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('application_date', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('job_resume_id_fkey', 'resume', ['resume_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('application_date')
        batch_op.drop_column('interview_date')
        batch_op.drop_column('salary_range')
        batch_op.drop_column('location')
        batch_op.drop_column('resume_id')

    # ### end Alembic commands ###
