"""Update db

Revision ID: e9b9cf9be65c
Revises: 80a9400b9df6
Create Date: 2026-02-11 23:04:38.446055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b9cf9be65c'
down_revision = '80a9400b9df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('job_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('status')
        batch_op.drop_column('job_url')
        batch_op.drop_column('company')

    # ### end Alembic commands ###
